/*CRIANDO NOVO PERFIL*/
CREATE ROLE novoPerfil;

/*CRIANDO NOVO USUÁRIO E ADICIONANDO AO PERFIL CRIADO ANTERIORMENTE*/
CREATE USER Gilson IDENTIFIED BY "senhaforte" DEFAULT ROLE novoPerfil;

/*DEFININDO O USUÁRIO CRIADO PARA APENAS PODER UTILIZAR O COMANDO SELECT*/
GRANT SELECT ON comabem.* TO Gilson;

/*AGORA TENTAR FAZER UM INSERÇÃO DE DADOS APRESENTARÁ UM ERRO POIS O USUÁRIO ESTÁ LIBERADO APENAS PARA SELECT*/
INSERT INTO Produtos(ds_produto, vl_produto, qt_produto, cd_unidade) VALUES ("Bolo de Chocolate", 20.00, 3, 2);